### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by curtchan** [muhdfaiz/js-loading-overlay#2]
Nice lib but it lacks one most important thing - ability to define target container.

**Comment by muhdfaiz** [comment]
@curtchan You mean you want it to appear within the container? Not full page.

If like that, I have the plan to add the feature. I will add this feature soon.

**Comment by muhdfaiz** [comment]
@curtchan I have added the feature you asking. It's available in version 1.1.0. I will close this issue.
