### ISSUE TITLE
Custom z-index

### ISSUE THREAD

**Issue by tidusIO** [muhdfaiz/js-loading-overlay#3]
Hey,
nice idea to develop a vanilla overlay module. Probably it's necessary to a customizable z-index. Sometimes you have embedded button or maps (paypal, google maps) with their own higher z-index.
-Tidus :D

**Comment by muhdfaiz** [comment]
@tidusIO I will add the custom z-index feature in the next update. probably by this weekend. Thank you for your input.

While waiting for the z-index feature available, you can use CSS for now to customize the default z-index.

**Comment by muhdfaiz** [comment]
@tidusIO I have added the option to specify custom z-index. I will close this issue. Available in version 1.2.0.
